### ISSUE TITLE
Update the current Team in the team.html

### ISSUE THREAD

**Issue by Signior-X** [E-Cell-IITMandi/E-Cell_Website#2]
Update the current team page, just add the three coordinators. and the rest of the team, as there are no heads, etc now.
Anyone interested can comment here.

**Comment by nivocadotoast** [comment]
interested

**Comment by Signior-X** [comment]
Ya sure go ahead!

One suggestion, if using VS code, try the live server extension, it will help a lot!

**Comment by nivocadotoast** [comment]
Okay, Thanks!

**Comment by khyati18** [comment]
Updated Team E-Cell 2020 by @WCoder007 :).
